### ISSUE TITLE
Add a command/program/bot to add/generate new commands/file template automatically?

### ISSUE THREAD

**Issue by LAPCoder** [SnabbGET/SnabbGET#22]
Hey @Yagi-404,

I think I should add a command/bot that edit a SnabbGET file to add a Macro, generate a function template in a file…

With this, the user (and I…) add his (my) own command directly and easily.

What you think about that?

**Comment by Yagi-404** [comment]
What do you mean ? You want to create a command for making custom commands ?
It's not a bad idea, you should keep it. But I think it's should be one of the last features we should add.

**Comment by Yagi-404** [comment]
Actually, when SG we'll be in v1.0, all the main features and additional ones. So only after using those commands, you'll be able to create new ones. In conclusion, it's a great idea but it should be the last command/feature we would add.
